CREATE TABLE IF NOT EXISTS employee
(uuid CHAR(36) NOT NULL, company_id INT NOT NULL, name NVARCHAR(16) NOT NULL, rank int NOT NULL);
ALTER TABLE employee ADD PRIMARY KEY (uuid, company_id);

CREATE TABLE IF NOT EXISTS company
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name NVARCHAR(60) NOT NULL);