DROP TABLE IF EXISTS share;
DROP TABLE IF EXISTS transaction;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS share;
DROP TABLE IF EXISTS application;
DROP TABLE IF EXISTS period;